(terpri)
(princ "Memory Layout for nth element")
(terpri)
(terpri)
(princ "Enter the list with parenthesis:")
(setq list (read))
(princ "Enter the value of n: ")
(setq n (read))
(princ "The element is: ")
(write (car (nthcdr (decf n 1) list)))
